// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdbmnevfqxmwhbwbdxmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYm1uZXZmcXhtd2hid2JkeG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwOTY2OTksImV4cCI6MjA4NDY3MjY5OX0.608mIr-TFe4sM_5X_0lXFLuV_eoR2xi3MmQ2WNGEYIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});